// AUTO-GENERATED by scripts/gen-project-stats.mjs — do not edit by hand.
// Numbers are derived from each app repo's settings.gradle.kts + Room DB over
// raw.githubusercontent. Run `npm run gen:stats` to refresh.
export const projectStats = {
  "mileway": {
    "modules": 35,
    "features": 13,
    "cores": 12,
    "dbVersion": 48,
    "screenshots": 159
  },
  "paymentslab": {
    "modules": 14,
    "providers": 0,
    "features": 4,
    "cores": 7,
    "screenshots": 26
  },
  "kursi": {
    "modules": 13,
    "screenshots": 51
  }
} as const;
